# # Copyright (c) 2025 Semtech Corporation
# # SPDX-License-Identifier: Apache-2.0

manifest:
  projects:
    - import: true
      name: usp_zephyr
      path: usp_zephyr
      url: https://github.com/Lora-net/usp_zephyr
      revision: v1.2.1

  self:
    path: swdm031_img_xfer